# -*- coding: utf-8 -*-
"""step_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a8YkQl7aLn8Wo94-2aWT6A5eNPtYRomm
"""

import json
import boto3
import os
import sys

def lambda_handler(event, context):
    aws_access_key= os.environ.get("aws_access_key")
    aws_access_password= os.environ.get("aws_access_password")
    client = boto3.client('emr', region_name='us-east-2',aws_access_key_id=aws_access_key,aws_secret_access_key=aws_access_password)
    file_name = event['Records'][0]['s3']['object']['key']
    bucketName=event['Records'][0]['s3']['bucket']['name']
    print("File Name : ",file_name)
    print("Bucket Name : ",bucketName)
    backend_code="s3://spotify-project-ljakka2/main.py"
    spark_submit = [
    'spark-submit',
    '--master', 'yarn',
    '--deploy-mode', 'cluster',
    backend_code,
    bucketName,
    file_name
    ]
    print("Spark Submit : ",spark_submit)
    cluster_id = client.run_job_flow(
    Name="transient_demo_testing",
    Instances={
    'InstanceGroups': [
    {
    'Name': "Master",
    'Market': 'ON_DEMAND',
    'InstanceRole': 'MASTER',
    'InstanceType': 'm5.xlarge',
    'InstanceCount': 1,
    },
    {
    'Name': "Slave",
    'Market': 'ON_DEMAND',
    'InstanceRole': 'CORE',
    'InstanceType': 'm5.xlarge',
    'InstanceCount': 2,
    }
    ],
    'Ec2KeyName': 'emer-first',
    'KeepJobFlowAliveWhenNoSteps': False,
    'TerminationProtected': False,
    'Ec2SubnetId': 'subnet-03733125bc1e769e4',
    },
    LogUri="s3://spotify-project-ljakka2/logs/",
    ReleaseLabel= 'emr-5.33.0',
    Steps=[{"Name": "testJobGURU",
    'ActionOnFailure': 'CONTINUE',
    'HadoopJarStep': {
    'Jar': 'command-runner.jar',
    'Args': spark_submit
    }
    }],
    BootstrapActions=[],
    VisibleToAllUsers=True,
    JobFlowRole="EMR_EC2_DefaultRole",
    ServiceRole="EMR_DefaultRole",
    Applications = [ {'Name': 'Spark'},{'Name':'Hive'}])
    print("Hello")

    return {'cluster_id': cluster_id}